const express = require("express");
const controller = require("../controllers/servicePagesController");

const router = express.Router();

router.get("/servico/incidentes", controller.incidentes);
router.get("/servico/incidentes/ficha", controller.incidenteFicha);
router.get("/servico/sla/politicas", controller.slaPoliticas);
router.get("/servico/sla/politicas/ficha", controller.slaPoliticasFicha);
router.get("/servico/sla/kpis", controller.slaKpis);
router.get("/servico/sla/kpis/ficha", controller.slaKpisFicha);
router.get("/servico/sla/instancias", controller.slaInstancias);
router.get("/servico/sla/instancias/ficha", controller.slaInstanciasFicha);
router.get("/servico/sla/instancias-kpi", controller.slaInstanciasKpi);
router.get("/servico/sla/instancias-kpi/ficha", controller.slaInstanciasKpiFicha);
router.get("/servico/sla/eventos", controller.slaEventos);
router.get("/servico/sla/eventos/ficha", controller.slaEventosFicha);
router.get("/servico/filas", controller.filas);
router.get("/servico/filas/ficha", controller.filasFicha);
router.get("/servico/filas/membros", controller.filasMembros);
router.get("/servico/filas/membros/ficha", controller.filasMembrosFicha);
router.get("/servico/ativos", controller.ativos);
router.get("/servico/ativos/ficha", controller.ativosFicha);
router.get("/servico/assuntos", controller.assuntos);
router.get("/servico/assuntos/ficha", controller.assuntosFicha);
router.get("/servico/calendarios", controller.calendarios);
router.get("/servico/calendarios/ficha", controller.calendariosFicha);
router.get("/servico/calendarios/regras", controller.calendariosRegras);
router.get("/servico/calendarios/regras/ficha", controller.calendariosRegrasFicha);
router.get("/servico/calendarios/excecoes", controller.calendariosExcecoes);
router.get("/servico/calendarios/excecoes/ficha", controller.calendariosExcecoesFicha);
router.get("/servico/agenda", controller.agendaAtividades);
router.get("/servico/schedule-board", controller.agendaBoard);
router.get("/servico/recursos", controller.recursos);
router.get("/servico/recursos/ficha", controller.recursosFicha);
router.get("/servico/recursos/agendamentos", controller.recursosAgendamentos);
router.get("/servico/recursos/agendamentos/ficha", controller.recursosAgendamentosFicha);
router.get("/servico/tarefas", controller.tarefas);
router.get("/servico/tarefas/ficha", controller.tarefasFicha);
router.get("/servico/tarefas/kanban", controller.tarefasKanban);
router.get("/servico/tarefas/tipos", controller.tarefasTipos);
router.get("/servico/tarefas/tipos/ficha", controller.tarefasTiposFicha);

module.exports = router;
